/**
 * Recipe type: canonical shape for API, AI-generated, and cached recipes.
 * Backward compatible: top-level calories/protein/carbs/fat remain for scoring;
 * optional macros/ingredients/steps used for full display and AI output.
 */

export interface RecipeMacros {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

export interface Recipe {
  id: string;
  name: string;
  /** Optional short description (API recipes). */
  description?: string;
  imageUrl?: string;
  /** Top-level macros for backward compatibility and scoring. */
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  servings?: number;
  cookTimeMinutes?: number;
  tags?: string[];
  createdAt?: string;
  updatedAt?: string;
  /** Full ingredients list (AI and enriched recipes). Default [] when absent. */
  ingredients?: string[];
  /** Cooking steps (AI and enriched recipes). Default [] when absent. */
  steps?: string[];
  /** Nested macros for display when present; otherwise use top-level. */
  macros?: RecipeMacros;
  /** Optional video link. */
  videoUrl?: string;
  /** True when generated by AI (for cache and dedup). */
  isAiGenerated?: boolean;
  /** Cuisine type (e.g. Italian, Mexican) for roulette display. */
  cuisineType?: string;
}

export type RecipeInput = Omit<
  Recipe,
  'id' | 'createdAt' | 'updatedAt'
>;

/**
 * Example Recipe matching the full interface (ingredients, steps, macros, videoUrl, isAiGenerated).
 * Used in docs and tests.
 */
export const EXAMPLE_RECIPE: Recipe = {
  id: 'example-1',
  name: 'Grilled Chicken with Herbed Rice',
  description: 'High-protein meal with fresh herbs.',
  calories: 420,
  protein: 38,
  carbs: 42,
  fat: 10,
  servings: 1,
  cookTimeMinutes: 35,
  tags: ['chicken', 'rice', 'high-protein'],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
  ingredients: [
    '1 boneless skinless chicken breast (6 oz)',
    '1/2 cup long-grain white rice',
    '1 cup chicken broth',
    '2 tbsp fresh parsley, chopped',
    '1 tbsp olive oil',
    'Salt and pepper to taste',
  ],
  steps: [
    'Season chicken with salt and pepper. Heat olive oil in a skillet over medium-high; cook chicken 6–7 min per side until 165°F.',
    'In a saucepan, bring broth to a boil. Add rice, reduce heat to low, cover, and cook 18 min.',
    'Fluff rice with a fork; stir in parsley. Serve chicken over rice.',
  ],
  macros: { calories: 420, protein: 38, carbs: 42, fat: 10 },
  videoUrl: 'https://example.com/grilled-chicken-rice',
  isAiGenerated: false,
};
